{{- if .Values.ollama.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    {{- include "adaptive-takehome.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ollama.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ollama.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.ollama.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.ollama.securityContext.runAsUser }}
      containers:
        - name: ollama
          image: "{{ .Values.ollama.image.repository }}:{{ .Values.ollama.image.tag }}"
          imagePullPolicy: {{ .Values.ollama.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.ollama.service.targetPort }}
            protocol: TCP
          resources:
            {{- toYaml .Values.ollama.resources | nindent 12 }}
          {{- if .Values.ollama.persistence.enabled }}
          volumeMounts:
          - name: ollama-data
            mountPath: {{ .Values.ollama.persistence.mountPath }}
          {{- end }}
        {{- if .Values.ollama.persistence.enabled }}
      volumes:
      - name: ollama-data
        hostPath:
          path: {{ .Values.ollama.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- end }}
{{- end }}
